# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-24 06:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fish',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('color', models.CharField(choices=[('0', 'Dark/gray'), ('1', 'Red')], max_length=2)),
                ('size', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('0', 'Correct'), ('1', 'Incorrect')], default='0', max_length=2)),
                ('active', models.BooleanField(default=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
